apiVersion: v1
data:
  config.yaml: |
    redis:
      host: redis.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      dbs:
        filtered_traces: 1
        scenarios: 2
        traces: 3
        executor_attr: 4
        pod_details: 7
        error_details: 8
    badger:
      filePath: /zk/badger
    server:
      host: 0.0.0.0
      port: 80
    traces:
      syncDurationMS: 1000
      syncBatchSize: 30
      ttl: 300
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-db-test
  labels:
    app: zk-db-test
    name: zk-db-test
  namespace: zk-client