apiVersion: v1
kind: Service
metadata:
  name: zk-db-test
  labels:
    app: zk-db-test
spec:
  selector:
    app: zk-db-test
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zk-db-test
  labels:
    app: zk-db-test
spec:
  selector:
    matchLabels:
      app: zk-db-test
  endpoints:
    - port: m-http
      path: /metrics
  namespaceSelector:
    any: true
