apiVersion: v1
kind: Service
metadata:
  name: zk-redis-test
  labels:
    app: zk-redis-test
spec:
  selector:
    app: zk-redis-test
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 80